import { MOCK_USER_ID } from "@/lib/constants";
import type { ContentGroup, Profile, Project, TimelineEntry } from "@/types/momentum";

/** Deterministic offsets so preview mode feels like a lived-in workspace. */
function isoMs(offsetMs: number) {
  return new Date(Date.now() + offsetMs).toISOString();
}

function dayOnly(offsetDays: number) {
  return new Date(Date.now() - offsetDays * 86400000).toISOString().slice(0, 10);
}

/** Shared demo group for cross-post comparison (Pro). */
export const MOCK_CROSS_POST_GROUP_ID = "c0000000-0000-4000-8000-000000000001";

export const mockContentGroups: ContentGroup[] = [
  {
    id: MOCK_CROSS_POST_GROUP_ID,
    user_id: MOCK_USER_ID,
    title: "Churn teardown — same story everywhere",
    description: "Reddit + Shorts + second subreddit test",
    created_at: isoMs(-86400000 * 10),
    updated_at: isoMs(-86400000 * 2),
  },
];

export const mockProfile: Profile = {
  id: MOCK_USER_ID,
  display_name: "Alex Builder",
  avatar_url: null,
  onboarding_completed: true,
  plan: "free",
  created_at: isoMs(-86400000 * 120),
  updated_at: isoMs(-3600000 * 2),
};

export const mockProjects: Project[] = [
  {
    id: "10000000-0000-4000-8000-000000000001",
    user_id: MOCK_USER_ID,
    name: "Morning habits",
    description:
      "Micro-habits for busy founders — daily nudges without the guilt spiral.",
    status: "building",
    logo_url: null,
    color: "#6366f1",
    icon: "Sparkles",
    created_at: isoMs(-86400000 * 34),
    updated_at: isoMs(-3600000 * 5),
  },
  {
    id: "10000000-0000-4000-8000-000000000002",
    user_id: MOCK_USER_ID,
    name: "Shared pantry",
    description:
      "Pantry inventory that actually stays updated. Barcode scan + household sharing.",
    status: "launched",
    logo_url: null,
    color: "#14b8a6",
    icon: "Package",
    created_at: isoMs(-86400000 * 95),
    updated_at: isoMs(-86400000 * 1),
  },
  {
    id: "10000000-0000-4000-8000-000000000003",
    user_id: MOCK_USER_ID,
    name: "Synth samples",
    description:
      "Retro synth one-shots and loops for Ableton & Logic — 90s hardware, modern mix.",
    status: "idea",
    logo_url: null,
    color: "#f97316",
    icon: "Zap",
    created_at: isoMs(-86400000 * 8),
    updated_at: isoMs(-86400000 * 3),
  },
];

export const mockTimelineEntries: TimelineEntry[] = [
  {
    id: "20000000-0000-4000-8000-000000000001",
    project_id: mockProjects[0].id,
    user_id: MOCK_USER_ID,
    type: "note",
    title: "Cut onboarding from 5 steps → 3",
    description:
      "Dropped email verification before first value; completion in beta jumped noticeably.",
    image_url: null,
    external_url: null,
    entry_date: dayOnly(1),
    platform: null,
    metrics: null,
    source_type: "manual",
    source_metadata: null,
    created_at: isoMs(-3600000 * 6),
    updated_at: isoMs(-3600000 * 6),
  },
  {
    id: "20000000-0000-4000-8000-000000000002",
    project_id: mockProjects[0].id,
    user_id: MOCK_USER_ID,
    type: "link",
    title: "New landing: social proof above fold",
    description: "Testimonials + logos before pricing; mobile hero tightened.",
    image_url: null,
    external_url: "https://example.com",
    entry_date: dayOnly(4),
    platform: null,
    metrics: null,
    source_type: "manual",
    source_metadata: null,
    created_at: isoMs(-86400000 * 4),
    updated_at: isoMs(-86400000 * 4),
  },
  {
    id: "20000000-0000-4000-8000-000000000003",
    project_id: mockProjects[1].id,
    user_id: MOCK_USER_ID,
    type: "snapshot",
    title: "App Store featuring Shared pantry",
    description:
      "Productivity category feature — installs 4× baseline for the week.",
    image_url: null,
    external_url: null,
    entry_date: dayOnly(11),
    platform: null,
    metrics: null,
    source_type: "manual",
    source_metadata: null,
    created_at: isoMs(-86400000 * 11),
    updated_at: isoMs(-86400000 * 11),
  },
  {
    id: "20000000-0000-4000-8000-000000000004",
    project_id: mockProjects[0].id,
    user_id: MOCK_USER_ID,
    type: "note",
    title: "Weekly active habit streaks",
    description:
      "Shipped streak UI + gentle reminders; watching retention cohort next.",
    image_url: null,
    external_url: null,
    entry_date: dayOnly(0),
    platform: null,
    metrics: null,
    source_type: "manual",
    source_metadata: null,
    created_at: isoMs(-3600000 * 2),
    updated_at: isoMs(-3600000 * 2),
  },
  {
    id: "20000000-0000-4000-8000-000000000005",
    project_id: mockProjects[2].id,
    user_id: MOCK_USER_ID,
    type: "note",
    title: "Sample pack #3 — Juno pads",
    description: "12 pads + 8 bass hits; targeting lofi & synthwave producers.",
    image_url: null,
    external_url: null,
    entry_date: dayOnly(3),
    platform: null,
    metrics: null,
    source_type: "manual",
    source_metadata: null,
    created_at: isoMs(-86400000 * 3),
    updated_at: isoMs(-86400000 * 3),
  },
  {
    id: "20000000-0000-4000-8000-000000000006",
    project_id: mockProjects[1].id,
    user_id: MOCK_USER_ID,
    type: "link",
    title: "Changelog: shared pantries",
    description: "Households can merge lists; resolved sync conflicts on low signal.",
    image_url: null,
    external_url: "https://example.com/changelog",
    entry_date: dayOnly(2),
    platform: null,
    metrics: null,
    source_type: "manual",
    source_metadata: null,
    created_at: isoMs(-86400000 * 2),
    updated_at: isoMs(-86400000 * 2),
  },
  {
    id: "30000000-0000-4000-8000-000000000001",
    project_id: mockProjects[0].id,
    user_id: MOCK_USER_ID,
    type: "distribution",
    title: "r/SaaS — “How I cut habit-app churn”",
    description:
      "Led with churn numbers, not features. DM’d 6 people who asked follow-up questions.",
    image_url: null,
    external_url: "https://reddit.com/r/SaaS/comments/example",
    entry_date: dayOnly(2),
    platform: "reddit",
    metrics: { views: 2100, likes: 140, comments: 38, promo_spend: 50 },
    content_group_id: MOCK_CROSS_POST_GROUP_ID,
    subreddit: "SaaS",
    source_type: "manual",
    source_metadata: null,
    created_at: isoMs(-86400000 * 2),
    updated_at: isoMs(-86400000 * 2),
  },
  {
    id: "30000000-0000-4000-8000-000000000002",
    project_id: mockProjects[0].id,
    user_id: MOCK_USER_ID,
    type: "distribution",
    title: "Build in public — onboarding before/after",
    description:
      "5-tweet thread with Loom clip. Saved as pinned for the week.",
    image_url: null,
    external_url: "https://x.com/example/status/123",
    entry_date: dayOnly(5),
    platform: "twitter",
    metrics: null,
    source_type: "manual",
    source_metadata: null,
    created_at: isoMs(-86400000 * 5),
    updated_at: isoMs(-86400000 * 5),
  },
  {
    id: "30000000-0000-4000-8000-000000000003",
    project_id: mockProjects[1].id,
    user_id: MOCK_USER_ID,
    type: "distribution",
    title: "Shared pantry 2.0 — Household lists",
    description:
      "Tuesday 12:01 AM PT launch. Maker comment every 2h first day.",
    image_url: null,
    external_url: "https://www.producthunt.com/posts/example",
    entry_date: dayOnly(14),
    platform: "product_hunt",
    metrics: null,
    source_type: "manual",
    source_metadata: null,
    created_at: isoMs(-86400000 * 14),
    updated_at: isoMs(-86400000 * 14),
  },
  {
    id: "30000000-0000-4000-8000-000000000004",
    project_id: mockProjects[1].id,
    user_id: MOCK_USER_ID,
    type: "distribution",
    title: "Reel: 15-sec pantry scan",
    description: "UGC-style demo; CTA to App Store in bio.",
    image_url: null,
    external_url: "https://instagram.com/p/example",
    entry_date: dayOnly(6),
    platform: "instagram",
    metrics: null,
    source_type: "manual",
    source_metadata: null,
    created_at: isoMs(-86400000 * 6),
    updated_at: isoMs(-86400000 * 6),
  },
  {
    id: "30000000-0000-4000-8000-000000000005",
    project_id: mockProjects[0].id,
    user_id: MOCK_USER_ID,
    type: "distribution",
    title: "Short: why micro-habits beat streak guilt",
    description:
      "First Short over 1k views; linked landing in description.",
    image_url: null,
    external_url: "https://youtube.com/watch?v=example",
    entry_date: dayOnly(8),
    platform: "youtube",
    metrics: { views: 4500, likes: 210, comments: 52 },
    content_group_id: MOCK_CROSS_POST_GROUP_ID,
    subreddit: null,
    source_type: "manual",
    source_metadata: null,
    created_at: isoMs(-86400000 * 8),
    updated_at: isoMs(-86400000 * 8),
  },
  {
    id: "30000000-0000-4000-8000-000000000009",
    project_id: mockProjects[0].id,
    user_id: MOCK_USER_ID,
    type: "distribution",
    title: "r/productivity — same churn angle",
    description: "Shorter hook; fewer comments than r/SaaS.",
    image_url: null,
    external_url: "https://reddit.com/r/productivity/comments/example2",
    entry_date: dayOnly(3),
    platform: "reddit",
    metrics: { views: 890, likes: 62, comments: 14 },
    content_group_id: MOCK_CROSS_POST_GROUP_ID,
    subreddit: "productivity",
    source_type: "manual",
    source_metadata: null,
    created_at: isoMs(-86400000 * 3),
    updated_at: isoMs(-86400000 * 3),
  },
  {
    id: "30000000-0000-4000-8000-000000000006",
    project_id: mockProjects[2].id,
    user_id: MOCK_USER_ID,
    type: "distribution",
    title: "POV: 808 through a SP-404",
    description: "Sound pack teaser; pinned comment with Gumroad link.",
    image_url: null,
    external_url: "https://tiktok.com/@example/video/123",
    entry_date: dayOnly(4),
    platform: "tiktok",
    metrics: null,
    source_type: "manual",
    source_metadata: null,
    created_at: isoMs(-86400000 * 4),
    updated_at: isoMs(-86400000 * 4),
  },
  {
    id: "30000000-0000-4000-8000-000000000007",
    project_id: mockProjects[0].id,
    user_id: MOCK_USER_ID,
    type: "distribution",
    title: "Indie Hackers milestone post",
    description:
      "500 users — shared MRR range + lessons on habit notifications.",
    image_url: null,
    external_url: "https://indiehackers.com/post/example",
    entry_date: dayOnly(1),
    platform: "other",
    metrics: null,
    source_type: "manual",
    source_metadata: null,
    created_at: isoMs(-3600000 * 18),
    updated_at: isoMs(-3600000 * 18),
  },
  {
    id: "30000000-0000-4000-8000-000000000008",
    project_id: mockProjects[1].id,
    user_id: MOCK_USER_ID,
    type: "distribution",
    title: "Customer quote — “finally shared the grocery list”",
    description:
      "Screenshot with permission; thread on household onboarding.",
    image_url: null,
    external_url: "https://x.com/example/status/456",
    entry_date: dayOnly(0),
    platform: "twitter",
    metrics: null,
    source_type: "manual",
    source_metadata: null,
    created_at: isoMs(-3600000 * 8),
    updated_at: isoMs(-3600000 * 8),
  },
  {
    id: "40000000-0000-4000-8000-000000000001",
    project_id: mockProjects[0].id,
    user_id: MOCK_USER_ID,
    type: "revenue",
    title: "MRR — subscriptions",
    description: "",
    image_url: null,
    external_url: null,
    entry_date: dayOnly(2),
    platform: null,
    metrics: null,
    amount: 4200,
    category: null,
    is_recurring: null,
    recurrence_label: null,
    revenue_source: "Subscriptions",
    partner_name: null,
    revenue_share_percentage: null,
    linked_distribution_entry_id: null,
    source_type: "manual",
    source_metadata: null,
    created_at: isoMs(-86400000 * 2),
    updated_at: isoMs(-86400000 * 2),
  },
  {
    id: "40000000-0000-4000-8000-000000000002",
    project_id: mockProjects[0].id,
    user_id: MOCK_USER_ID,
    type: "revenue",
    title: "Workshop ticket sales",
    description: "",
    image_url: null,
    external_url: null,
    entry_date: dayOnly(5),
    platform: null,
    metrics: null,
    amount: 890,
    category: null,
    is_recurring: null,
    recurrence_label: null,
    revenue_source: "Events",
    partner_name: null,
    revenue_share_percentage: null,
    linked_distribution_entry_id: null,
    source_type: "manual",
    source_metadata: null,
    created_at: isoMs(-86400000 * 5),
    updated_at: isoMs(-86400000 * 5),
  },
  {
    id: "40000000-0000-4000-8000-000000000006",
    project_id: mockProjects[0].id,
    user_id: MOCK_USER_ID,
    type: "revenue",
    title: "💰 $320.00 — Reddit thread",
    description: "",
    image_url: null,
    external_url: null,
    entry_date: dayOnly(1),
    platform: null,
    metrics: null,
    amount: 320,
    category: null,
    is_recurring: null,
    recurrence_label: null,
    revenue_source: "Reddit thread",
    partner_name: null,
    revenue_share_percentage: null,
    linked_distribution_entry_id: "30000000-0000-4000-8000-000000000001",
    source_type: "manual",
    source_metadata: null,
    created_at: isoMs(-86400000 * 1),
    updated_at: isoMs(-86400000 * 1),
  },
  {
    id: "40000000-0000-4000-8000-000000000003",
    project_id: mockProjects[0].id,
    user_id: MOCK_USER_ID,
    type: "cost",
    title: "Hosting & CDN",
    description: "",
    image_url: null,
    external_url: null,
    entry_date: dayOnly(1),
    platform: null,
    metrics: null,
    amount: 480,
    category: "Infrastructure",
    is_recurring: true,
    recurrence_label: "Monthly",
    revenue_source: null,
    partner_name: null,
    revenue_share_percentage: null,
    linked_distribution_entry_id: null,
    source_type: "manual",
    source_metadata: null,
    created_at: isoMs(-86400000 * 1),
    updated_at: isoMs(-86400000 * 1),
  },
  {
    id: "40000000-0000-4000-8000-000000000004",
    project_id: mockProjects[0].id,
    user_id: MOCK_USER_ID,
    type: "cost",
    title: "Design tools",
    description: "",
    image_url: null,
    external_url: null,
    entry_date: dayOnly(3),
    platform: null,
    metrics: null,
    amount: 65,
    category: "Software",
    is_recurring: true,
    recurrence_label: "Monthly",
    revenue_source: null,
    partner_name: null,
    revenue_share_percentage: null,
    linked_distribution_entry_id: null,
    source_type: "manual",
    source_metadata: null,
    created_at: isoMs(-86400000 * 3),
    updated_at: isoMs(-86400000 * 3),
  },
  {
    id: "40000000-0000-4000-8000-000000000005",
    project_id: mockProjects[0].id,
    user_id: MOCK_USER_ID,
    type: "deal",
    title: "🤝 15% — Launch Partner Co",
    description: "",
    image_url: null,
    external_url: null,
    entry_date: dayOnly(4),
    platform: null,
    metrics: null,
    amount: null,
    category: null,
    is_recurring: null,
    recurrence_label: null,
    revenue_source: null,
    partner_name: "Launch Partner Co",
    revenue_share_percentage: 15,
    linked_distribution_entry_id: null,
    source_type: "manual",
    source_metadata: null,
    created_at: isoMs(-86400000 * 4),
    updated_at: isoMs(-86400000 * 4),
  },
];
